apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-replicaset
  labels:
    app: nginx
    tier: nginx-server
spec:
  # we want 3 replicas
  replicas: 3
  selector:
    matchLabels:
      # we will look for the label tier with the value nginx-server
      tier: nginx-server
  # the template that describes our pod
  template:
    metadata:
      labels:
        tier: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
